/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Aug 10 10:01:07 GMT 2026
 */

package org.apache.syncope.core.spring.security.jws;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class AccessTokenJWSVerifier_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.syncope.core.spring.security.jws.AccessTokenJWSVerifier"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    /*No java.lang.System property to set*/
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(AccessTokenJWSVerifier_ESTest_scaffolding.class.getClassLoader() ,
      "com.nimbusds.jose.util.ByteUtils",
      "com.nimbusds.jose.JOSEProvider",
      "com.nimbusds.jose.crypto.impl.RSASSAProvider",
      "com.nimbusds.jose.JWSProvider",
      "com.nimbusds.jose.JOSEException",
      "com.nimbusds.jose.crypto.impl.BaseJWSProvider",
      "com.nimbusds.jose.util.StandardCharset",
      "org.apache.commons.lang3.StringUtils",
      "com.nimbusds.jose.jca.JCAAware",
      "com.nimbusds.jose.crypto.impl.CriticalHeaderParamsDeferral",
      "com.nimbusds.jose.shaded.jcip.Immutable",
      "com.nimbusds.jose.crypto.MACVerifier",
      "com.nimbusds.jose.Header",
      "com.nimbusds.jose.crypto.RSASSAVerifier",
      "com.nimbusds.jose.util.Base64URL",
      "com.nimbusds.jose.crypto.impl.MACProvider",
      "com.nimbusds.jose.util.ArrayUtils",
      "org.apache.syncope.core.spring.security.jws.AccessTokenJWSVerifier",
      "com.nimbusds.jose.util.Base64",
      "com.nimbusds.jose.CriticalHeaderParamsAware",
      "com.nimbusds.jose.util.Base64Codec",
      "com.nimbusds.jose.JWSVerifier",
      "com.nimbusds.jose.JWEHeader",
      "com.nimbusds.jose.JWSAlgorithm",
      "com.nimbusds.jose.util.IntegerOverflowException",
      "com.nimbusds.jose.JWSHeader",
      "com.nimbusds.jose.CommonSEHeader",
      "com.nimbusds.jose.Requirement",
      "com.nimbusds.jose.jca.JCAContext",
      "com.nimbusds.jose.KeyException",
      "com.nimbusds.jose.JWSAlgorithm$Family",
      "com.nimbusds.jose.AlgorithmFamily",
      "com.nimbusds.jose.Algorithm",
      "com.nimbusds.jose.KeyLengthException"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(AccessTokenJWSVerifier_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.syncope.core.spring.security.jws.AccessTokenJWSVerifier",
      "com.nimbusds.jose.AlgorithmFamily",
      "com.nimbusds.jose.Requirement",
      "com.nimbusds.jose.Algorithm",
      "com.nimbusds.jose.JWSAlgorithm",
      "com.nimbusds.jose.util.ArrayUtils",
      "com.nimbusds.jose.JWSAlgorithm$Family",
      "com.nimbusds.jose.util.JSONStringUtils",
      "com.nimbusds.jose.crypto.impl.BaseJWSProvider",
      "com.nimbusds.jose.crypto.impl.MACProvider",
      "com.nimbusds.jose.crypto.MACVerifier",
      "com.nimbusds.jose.util.StandardCharset",
      "com.nimbusds.jose.util.ByteUtils",
      "com.nimbusds.jose.jca.JCAContext",
      "com.nimbusds.jose.JOSEException",
      "com.nimbusds.jose.KeyException",
      "com.nimbusds.jose.KeyLengthException",
      "com.nimbusds.jose.util.Base64",
      "com.nimbusds.jose.util.Base64URL",
      "com.nimbusds.jose.util.Base64Codec",
      "com.nimbusds.jose.jwk.JWK",
      "com.nimbusds.jose.Header",
      "com.nimbusds.jose.CommonSEHeader",
      "com.nimbusds.jose.JWSHeader",
      "com.nimbusds.jose.util.JSONObjectUtils",
      "com.nimbusds.jose.JOSEObjectType",
      "com.nimbusds.jose.UnprotectedHeader",
      "com.nimbusds.jose.crypto.impl.CriticalHeaderParamsDeferral",
      "org.apache.commons.lang3.StringUtils",
      "com.nimbusds.jose.util.X509CertUtils",
      "com.nimbusds.jose.util.BigIntegerUtils",
      "com.nimbusds.jose.crypto.impl.RSASSAProvider",
      "com.nimbusds.jose.crypto.RSASSAVerifier",
      "com.nimbusds.jose.jwk.PEMEncodedKeyParser",
      "com.nimbusds.jose.jwk.KeyRevocation"
    );
  }
}
